# Generated by Django 5.2 on 2025-08-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cycle_min', models.IntegerField(blank=True, null=True)),
                ('cycle_max', models.IntegerField(blank=True, null=True)),
                ('rendement_min_t_ha', models.FloatField(blank=True, null=True)),
                ('rendement_max_t_ha', models.FloatField(blank=True, null=True)),
                ('quantite_semence_g_ha', models.FloatField(blank=True, null=True)),
                ('type_culture', models.CharField(choices=[('conventionnel', 'Conventionnel'), ('bio', 'Biologique')], default='conventionnel', max_length=20)),
                ('saisonnalite', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cultures/')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField()),
                ('type_engrais', models.CharField(max_length=100)),
                ('dose_ha', models.CharField(max_length=100)),
                ('mode_application', models.CharField(blank=True, max_length=100, null=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='fertilisations/')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPhytosanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=100)),
                ('matiere_active', models.CharField(max_length=100)),
                ('type_produit', models.CharField(choices=[('fongicide', 'Fongicide'), ('insecticide', 'Insecticide'), ('bactericide', 'Bactéricide')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits_phytos/')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('frequence', models.CharField(max_length=50)),
                ('delai_apres_plantation', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='etapes/')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelle.culture')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('app', 'App')], default='app', max_length=20)),
                ('envoyee', models.BooleanField(default=False)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='farm_management.farm')),
            ],
        ),
        migrations.CreateModel(
            name='TraitementPhytosanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField()),
                ('type_traitement', models.CharField(max_length=100)),
                ('cible', models.CharField(max_length=100)),
                ('matiere_active', models.CharField(blank=True, max_length=100, null=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='traitements/')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_utilises', to='parcelle.produitphytosanitaire')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plantation', models.DateField()),
                ('climat', models.CharField(blank=True, max_length=100, null=True)),
                ('type_sol', models.CharField(blank=True, max_length=100, null=True)),
                ('surface_ha', models.FloatField(blank=True, null=True)),
                ('type_culture', models.CharField(blank=True, choices=[('conventionnel', 'Conventionnel'), ('bio', 'Biologique')], max_length=20, null=True)),
                ('saison', models.CharField(blank=True, max_length=50, null=True)),
                ('rendement_min', models.FloatField(blank=True, null=True)),
                ('rendement_max', models.FloatField(blank=True, null=True)),
                ('semences_necessaires_g', models.FloatField(blank=True, null=True)),
                ('etapes', models.ManyToManyField(blank=True, to='parcelle.etapeculture')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='farm_management.farm')),
                ('fertilisations', models.ManyToManyField(blank=True, to='parcelle.fertilisation')),
                ('traitements', models.ManyToManyField(blank=True, to='parcelle.traitementphytosanitaire')),
            ],
        ),
        migrations.CreateModel(
            name='CalendrierCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField()),
                ('alerte_envoyee', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelle.etapeculture')),
                ('fertilisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelle.fertilisation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelle.parcelle')),
                ('traitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelle.traitementphytosanitaire')),
            ],
        ),
        migrations.CreateModel(
            name='Variete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('distance_plantation', models.CharField(max_length=50)),
                ('rendement_min', models.FloatField(blank=True, null=True)),
                ('rendement_max', models.FloatField(blank=True, null=True)),
                ('quantite_semence_ha', models.FloatField(blank=True, null=True)),
                ('periode_culture', models.CharField(blank=True, max_length=100, null=True)),
                ('besoins_eau', models.TextField(blank=True, null=True)),
                ('techniques_greffage', models.TextField(blank=True, null=True)),
                ('maladies_frequentes', models.TextField(blank=True, null=True)),
                ('produits_recommandes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='varietes/')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varietes', to='parcelle.culture')),
            ],
        ),
        migrations.AddField(
            model_name='traitementphytosanitaire',
            name='variete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='parcelle.variete'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='variete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelle.variete'),
        ),
        migrations.AddField(
            model_name='fertilisation',
            name='variete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilisations', to='parcelle.variete'),
        ),
    ]
